[project]
name = "opencaption-4b-vl-sft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Prithiv Sakthi U R", email = "prithivsakthi676@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "accelerate==1.14.0",
    "av==17.1.0",
    "einops==0.8.2",
    "gradio==6.25.0",
    "kernels==0.16.0",
    "matplotlib==3.10.9",
    "opencv-python==5.0.0.93",
    "peft==0.20.0",
    "pillow==12.3.0",
    "qwen-vl-utils==0.0.14",
    "sentencepiece==0.2.2",
    "spaces==0.51.1",
    "timm==1.0.28",
    "torch==2.11.0",
    "torchvision==0.26.0",
    "transformers==5.16.1",
    "transformers-stream-generator==0.0.5",
]

[project.scripts]
opencaption-4b-vl-sft = "opencaption_4b_vl_sft:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
